# Generated by Buildr 1.4.6, change to your liking
require 'buildr/scala'

def setup_growl
  require 'ruby_gntp'

  # Growl setup
  Buildr.application.on_completion do |title, message|
    GNTP.notify({
      :app_name => "buildr",
      :title    => title, 
      :text     => message,
    })
  end

  Buildr.application.on_failure do |title, message|
    GNTP.notify({
      :app_name => "buildr",
      :title    => title, 
      :text     => message,
    })
  end
end

setup_growl

# Version number for this release
VERSION_NUMBER = "1.0.0"

# Group identifier for your projects
GROUP = "echo"
COPYRIGHT = "Callum Stott 2012"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

# Project setup
Project.local_task :typeset
Project.local_task :tcc
Project.local_task :console

define "echo" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  package :jar
  test.using :specs
  
  task :typeset do
    FileUtils.makedirs('target/pdfs') unless File.exists?('target/pdfs')
    system 'xelatex -output-directory=target/pdfs -shell-escape src/report/echo.tex'
    system 'open target/pdfs/echo.pdf'
  end
  
  task :tcc => :typeset do
    FileUtils.makedirs('target/pdfs') unless File.exists?('target/pdfs')
    system 'kicker -e "xelatex -output-directory=target/pdfs -shell-escape src/report/echo.tex" src/report/echo.tex'
  end
  
  task :console => :compile do
    system 'scala -classpath target:target/classes'
  end
end