# Generated by Buildr 1.4.6, change to your liking
require 'buildr/scala'

# Version number for this release
VERSION_NUMBER = "0.10.0"

# Group identifier for your projects
GROUP = "echo"
COPYRIGHT = "Callum Stott 2011"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

Project.local_task :typeset
Project.local_task :console

define "echo" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  package :jar
  test.using :specs
  
  task :typeset do
    FileUtils.makedirs('target/pdfs') unless File.exists?('target/pdfs')
    system 'xelatex -output-directory=target/pdfs src/report/*.tex'
  end
  
  task :console => :compile do
    system 'scala -classpath target:target/classes'
  end
end
